services:
  node-dev-for-app:
    build: .  # Builds the image using the Dockerfile in the current directory
    image: react-ts-dock
    container_name: react-ts
    ports:
      - 3000:3000
    volumes:
      - .:/home/devuser/react-ts  # Mount current directory into the container
    working_dir: /home/devuser/react-ts
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NVM_DIR=/home/devuser/.nvm
    tty: true  # For interactive bash sessions
    user: "101:101"  # Use UID:GID instead of username `devuser` (with `devgroup`)  (in Bitnami/Minideb Debian)
